name: easy_kasir
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" # Diperbarui untuk mendukung versi terbaru

dependencies:
  flutter:
    sdk: flutter

  # Versi terbaru yang stabil dan kompatibel
  image_picker: ^1.1.1
  permission_handler: ^12.0.1
  intl: ^0.19.0
  image: ^4.2.0
  flutter_image_compress: ^2.2.0
  path_provider: ^2.1.3
  open_filex: ^4.4.0
  syncfusion_flutter_datepicker: ^26.2.4
  pdf: ^3.10.7
  http: ^1.2.1 # Versi ini diperlukan oleh firebase_auth terbaru
  file_picker: ^8.0.0
  firebase_core: ^3.2.0
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.0.0
  google_sign_in: ^6.2.1
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/gambar1.jpeg
    - assets/auth/client_secret_441446128484-42abolk84d34id01fois2992anfeqmu0.apps.googleusercontent.com.json
