// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9vppgkhnwCOayX8FuD7x5p7FN-3jWyQY',
    appId: '1:441446128484:web:7f512510ccfd5f2faa3871',
    messagingSenderId: '441446128484',
    projectId: 'easykasir-cc9b8',
    authDomain: 'easykasir-cc9b8.firebaseapp.com',
    storageBucket: 'easykasir-cc9b8.firebasestorage.app',
    measurementId: 'G-86W70XMCTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIpdFn1MKbIwy31K5vRBsQeJQfJbZeF8M',
    appId: '1:441446128484:android:8a019dd38bb94008aa3871',
    messagingSenderId: '441446128484',
    projectId: 'easykasir-cc9b8',
    storageBucket: 'easykasir-cc9b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6JHy8wilY2uSbjG4uFygJtMSGqQh6BLE',
    appId: '1:441446128484:ios:623304d966ba8cdfaa3871',
    messagingSenderId: '441446128484',
    projectId: 'easykasir-cc9b8',
    storageBucket: 'easykasir-cc9b8.firebasestorage.app',
    androidClientId: '441446128484-42abolk84d34id01fois2992anfeqmu0.apps.googleusercontent.com',
    iosClientId: '441446128484-7d5obs09k3chiptuib7omcn8kloactmj.apps.googleusercontent.com',
    iosBundleId: 'com.example.easyKasir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6JHy8wilY2uSbjG4uFygJtMSGqQh6BLE',
    appId: '1:441446128484:ios:623304d966ba8cdfaa3871',
    messagingSenderId: '441446128484',
    projectId: 'easykasir-cc9b8',
    storageBucket: 'easykasir-cc9b8.firebasestorage.app',
    androidClientId: '441446128484-42abolk84d34id01fois2992anfeqmu0.apps.googleusercontent.com',
    iosClientId: '441446128484-7d5obs09k3chiptuib7omcn8kloactmj.apps.googleusercontent.com',
    iosBundleId: 'com.example.easyKasir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9vppgkhnwCOayX8FuD7x5p7FN-3jWyQY',
    appId: '1:441446128484:web:79e9ee87b92c3f18aa3871',
    messagingSenderId: '441446128484',
    projectId: 'easykasir-cc9b8',
    authDomain: 'easykasir-cc9b8.firebaseapp.com',
    storageBucket: 'easykasir-cc9b8.firebasestorage.app',
    measurementId: 'G-C1PGVV6T72',
  );
}
